### ISSUE TITLE
Software disabled

### ISSUE THREAD

**Issue by fa225909** [pbludov/hv-ms735-config#1]
Hello,

Although the mouse works perfectly, have a problem with the hv-ms735-config, no tab is activated (exept the "about" tab) even after restart.
![sans nom 1](https://user-images.githubusercontent.com/35639861/35188106-2f00cffc-fe30-11e7-902d-29c542b2b2b3.png)

I also see it with lsusb :

> ~$ lsusb
> Bus 002 Device 003: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
> Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 008 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 007 Device 005: ID 0a5c:3503 Broadcom Corp. 
> Bus 007 Device 004: ID 0a5c:3502 Broadcom Corp. 
> Bus 007 Device 003: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
> Bus 007 Device 002: ID 0a12:3535 Cambridge Silicon Radio, Ltd 
> Bus 007 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 001 Device 004: ID 1a40:0101 Terminus Technology Inc. Hub
> Bus 001 Device 003: ID 0e8d:1806 MediaTek Inc. Samsung SE-208 Slim Portable DVD Writer
> Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> **Bus 003 Device 004: ID 04d9:a100 Holtek Semiconductor, Inc.** 
> Bus 003 Device 003: ID 0c45:760a Microdia 
> Bus 003 Device 002: ID 0409:0058 NEC Corp. HighSpeed Hub
> Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I use ubuntu mate 17.10

thank you for your help.

**Comment by pbludov** [comment]
The possible cause is that libhid has been updated in Ubuntu 17.10.

Please, provide some more details. Are you using a hub?

**Comment by pbludov** [comment]
@fa225909 the bug is confirmed.
For some unknown reason the root access is required to run the software in Ubuntu 17.10, i.e.
`sudo hv-ms735-config` works fine, while `hv-ms735-config` doesn't. I will investigate this problem.

**Comment by pbludov** [comment]
New release has been published in 
https://launchpad.net/%7Epbludov/+archive/ubuntu/ppa
(Packages for Ubuntu 16.04 and Ubuntu 17.10 only).
Please upgrade the software and check it.

**Comment by fa225909** [comment]
now it works, thank you very much

2018-01-21 4:31 GMT+01:00 pbludov <notifications@github.com>:
